src/newspaperizer/urls.py
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin

urlpatterns = i18n_patterns(
    # '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls')),
    url(r'^world/', include('world.urls')),
    url(r'^book/', include('book.urls')),
    url(r'^newspaper/', include('newspaper.urls')),
    url(r'^article/', include('article.urls')),
    url(r'^pdf/', include('pdf.urls')),
    url(r'^wiki/', include('wiki.urls')),
    url(r'', include('index.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/pdf/urls.py
#coding: utf-8
from django.conf.urls import url
from pdf.views import pdf_view


urlpatterns = [
    url(r'^(?P<np>[\w-]+)/(?P<year>\d+)/(?P<issue>\d+)/view.pdf$', pdf_view, name='pdf'),
]

src/world/urls.py
# coding: utf-8
from django.conf.urls import url
from world.views import WorldListView, WikiListView, WorldDetailView, random_world, OrphanView


urlpatterns = [
    url(r'^$', WorldListView.as_view(), name='worlds'),
    url(r'^__page.opt$', WikiListView.as_view(), name='worlds_wiki'),
    url(r'^random/$', random_world, name='random_world'),
    url(r'^orphans/$', OrphanView.as_view(), name='world_orphans'),
    url(r'^(?P<slug>[\w-]+)/view/$', WorldDetailView.as_view(), name='world'),
]

src/world/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.utils.safestring import mark_safe
from newspaperizer.settings import settings
from django.core.files.storage import FileSystemStorage
from wiki.models import WikiPage

image_fs = FileSystemStorage(
    location=settings.get('worlds', dict()).get('images_root'),
    base_url=settings.get('worlds', dict()).get('images_url'),
)


class World(models.Model):
    title = models.CharField(_('Title'), max_length=255, blank=False)
    slug = models.SlugField(_('Slug'), unique=True)
    image = models.ImageField(verbose_name=_('Image'), storage=image_fs)  # upload_to=settings.get('worlds', dict()).get('images', 'images'))
    rating = models.PositiveIntegerField(_('Rating'), default=0)

    def __unicode__(self):
        print(self.image.url)
        return self.title

    def __str__(self):
        return self.__unicode__()

    def get_absolute_url(self):
        return reverse('world', args=[self.slug])

    def preview(self):
        return mark_safe('<img src="{}" />'.format(self.image.url))

    preview.short_description = _('Image')

    def get_attach_filename(self):
        import os
        return os.path.basename(self.image.name)

    def get_wiki(self):
        wiki_root = settings.get('worlds', dict()).get('wiki_root')
        attach_url = settings.get('worlds', dict()).get('attach_url')
        wiki_path = settings.get('worlds', dict()).get('wiki_path')

        w = WikiPage(root=wiki_root)
        w.root_url = reverse("path", kwargs={'path': wiki_path, })
        # "{}{}".format(reverse("wikiroot"), wiki_path)
        w.load(path="{}/".format(self.title))

        import logging
        logging.debug("Wiki Root: %s", wiki_root)
        return w
        # return load_wiki(wiki_root, self.title, attach="{}{}/__attach/".format(attach_url, self.title), href=reverse("wiki", kwargs={'path': "Миры/{}".format(self.title)}))

    def prev(self):
        try:
            return World.objects.filter(id__lt=self.id).order_by('-id')[0]
        except (IndexError):
            return None

    def next(self):
        try:
            return World.objects.filter(id__gt=self.id).order_by('id')[0]
        except (IndexError):
            return None

    class Meta:
        verbose_name = _('world')
        verbose_name_plural = _('worlds')
        ordering = ['-rating', 'title', ]

src/world/views.py
from django.views.generic import ListView, DetailView, TemplateView
from newspaperizer.settings import settings
from world.models import World
from django.shortcuts import redirect


def random_world(request):
    world = World.objects.order_by('?').first()
    return redirect(world.get_absolute_url())


class OrphanView(TemplateView):
    template_name = 'world/orphans_list.html'
    path = settings.get('worlds', dict()).get('wiki_root', "../media/worlds")

    def get_orphans(self):
        import os
        try:
            items = next(os.walk(self.path))[1]
        except StopIteration:
            items = []
        items = list(filter(lambda f: not f.startswith('.') and not f.startswith('__') and not World.objects.filter(title=f).exists(), items))
        return items

    def get_context_data(self, **kwargs):
        context = super(OrphanView, self).get_context_data(**kwargs)
        context['orphans'] = self.get_orphans()
        return context


class WorldListView(ListView):
    model = World


class WikiListView(ListView):
    model = World
    template_name = 'world/wiki_list.html'


class WorldDetailView(DetailView):
    model = World

    def get_object(self, queryset=None):
        obj = super(WorldDetailView, self).get_object(queryset)
        obj.rating += 1
        obj.save()
        return obj

templates/world/orphans_list.html
{% extends 'world/world_list.html' %} 
{% load django_bootstrap_breadcrumbs %}
{% load i18n %}
{% block jquery %}
var $grid = $(".wall").masonry({
  itemSelector: ".brick",
  columnWidth: 300
});

$grid.imagesLoaded().progress(function() {
  $grid.masonry('layout');
});
{% endblock %}
{% block title %}{% trans "Orphans" %}{% endblock %} 
{% block breadcrumbs %}
	{{ block.super }}
	{% breadcrumb "Orphans" "world_orphans" %}
{% endblock %}
{% block pagehead %}
<div class="container">
  <h1 class="col-md-10">{% trans "Orphans" %}</h1>
</div>
{% endblock %}
{% block content %}
{% if orphans %}
  <ul class="wall container">
	{% for orphan in orphans %}
    <li class="brick"><a href="{{ orphan }}">
        <h5>{{ orphan }}</h5>
    </a></li>
	{% endfor %}
  </ul>
{% endif %}
{% endblock %}

templates/world/wiki_list.html
{% load i18n %}
<pre>
!! {% trans "Worlds" %}

{% for world in object_list %}* [[Attach:{{ world.get_attach_filename }} -> {{ world.title }}]][[<<]]{{ world.title }}
{% endfor %}
(:childlist:)
</pre>

templates/world/world_detail.html
{% extends 'world/world_list.html' %}
{% load django_bootstrap_breadcrumbs %} 
{% load i18n %}
{% block title %} {{ world }} {% endblock %} 
{% block breadcrumbs %}
	{{ block.super }}
	{% breadcrumb world.title world.get_absolute_url %}
{% endblock %}
{% block prev %}<a{% if world.prev %} href="{{ world.prev.get_absolute_url }}"{% endif %} class="btn btn-default">{% if world.prev %}{{ world.prev.title }}{% endif %}</a>{% endblock %}
{% block next %}<a{% if world.next %} href="{{ world.next.get_absolute_url }}"{% endif %} class="btn btn-default">{% if world.next %}{{ world.next.title }}{% endif %}</a>{% endblock %}
{% block pagehead %}
<div class="container">
  <h1 class="col-md-10">
    {{ world.title }}
  </h1>
  <ul class="edit-btns">
    <li><a href="{% url "admin:world_world_add" %}" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> {% trans "Add" %}</a></li>
    <li><a href="{% url "admin:world_world_change" world.id %}" class="btn btn-default"><span class="glyphicon glyphicon-pencil"></span> {% trans "Change" %}</a></li>
  </ul>
</div>
{% endblock %}
{% block content %}
<div class="col-md-3">
  <img src="{{ world.image.url }}" alt="{{ world.title }}" />
  <ul>
    <li><a href="//google.com/search?q={{ world.title }}">Google</a></li>
    <li><a href="//wikipedia.org/wiki/{{ world.title }}">Wikipedia</a></li>
    <li><a href="//ru.rpg.wikia.com/wiki/{{ world.title }}">RPG Wikia</a></li>
  </ul>
{{ world.description | linebreaks }}
</div>
<div class="col-md-9">
{{ world.get_wiki.get_html | safe }}
</div>
{% endblock %}

templates/world/world_list.html
{% extends 'base.html' %} 
{% load django_bootstrap_breadcrumbs %}
{% load i18n %}
{% block jquery %}
var $grid = $(".wall").masonry({
  itemSelector: ".brick",
  columnWidth: 275
});

$grid.imagesLoaded().progress(function() {
  $grid.masonry('layout');
});
{% endblock %}
{% block title %}{% trans "Worlds" %}{% endblock %} 
{% block breadcrumbs %}
	{{ block.super }}
	{% breadcrumb "Worlds" "worlds" %}
{% endblock %}
{% block pagehead %}
<div class="container">
  <h1 class="col-md-10">{% trans "Worlds" %}</h1>
</div>
{% endblock %}
{% block content %}
  <ul class="wall container">
    <li class="brick"><a href="{% url "admin:world_world_add" %}"><h1><span class="glyphicon glyphicon-plus"></span> {% trans "Add" %}</h1></a></li>
    <li class="brick"><a href="{% url "worlds_wiki" %}"><h1>Wiki</h1></a></li>
    <li class="brick"><a href="{% url "world_orphans" %}"><h1>{% trans "Orphans" %}</h1></a></li>
{% if object_list %}
    <li class="brick"><a href="{% url "random_world" %}"><h1>{% trans "Random" %}</h1></a></li>
	{% for world in object_list %}
    <li class="brick"><a href="{{ world.get_absolute_url }}">
        <h5>{{ world.title }}</h5>
        {{ world.preview }}
    </a></li>
	{% endfor %}
{% endif %}
  </ul>
{% endblock %}