src/book/urls.py
# coding: utf-8
from django.conf.urls import url
from book.views import random_book, GenreListView, WikiListView, GenreView, BookListView, BookView


urlpatterns = [
    url(r'^$', GenreListView.as_view()),

    url(r'^genre/$', GenreListView.as_view(), name='book_genres'),
    url(r'^orphans/$', GenreView.as_view(), name='book_genres_orphans'),

    url(r'^genre/(?P<slug>[\w-]+)/$', GenreView.as_view(), name='book_genre'),

    url(r'^genre/__page.opt$', WikiListView.as_view(), name='book_genres_wiki'),
    url(r'^genre/(?P<slug>[\w-]+)/__page.opt$', WikiListView.as_view(), name='book_genre_wiki'),

    url(r'^random/(?P<genre>[\w-]+)?/?$', random_book, name='random_book'),
    url(r'^book/$', BookListView.as_view(), name='books'),
    url(r'^book/(?P<slug>[\w-]+)/$', BookView.as_view(), name='book'),

]

src/newspaperizer/urls.py
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin

urlpatterns = i18n_patterns(
    # '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls')),
    url(r'^world/', include('world.urls')),
    url(r'^book/', include('book.urls')),
    url(r'^newspaper/', include('newspaper.urls')),
    url(r'^article/', include('article.urls')),
    url(r'^pdf/', include('pdf.urls')),
    url(r'^wiki/', include('wiki.urls')),
    url(r'', include('index.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/pdf/urls.py
#coding: utf-8
from django.conf.urls import url
from pdf.views import pdf_view


urlpatterns = [
    url(r'^(?P<np>[\w-]+)/(?P<year>\d+)/(?P<issue>\d+)/view.pdf$', pdf_view, name='pdf'),
]

src/book/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from newspaperizer.settings import settings
from django.core.files.storage import FileSystemStorage
from people.models import Person


config = settings.get('books', dict())
path = config.get('path', '')


image_fs = FileSystemStorage(
    location=config.get('images_root'),
    base_url=config.get('images_url'),
)


genre_image_fs = FileSystemStorage(
    location=config.get('genres', dict()).get('images_root'),
    base_url=config.get('genres', dict()).get('images_url'),
)


class BookGenre(models.Model):
    subgenres = models.ManyToManyField('self', verbose_name=_('Subgenre'), blank=True, symmetrical=False)
    title = models.CharField(_('Title'), max_length=255)
    slug = models.SlugField(_('Slug'), unique=True)
    folder = models.CharField(_('Folder'), max_length=255, blank=True)
    image = models.ImageField(verbose_name=_('Image'), storage=genre_image_fs, blank=True)
    description = models.TextField(_('Description'), max_length=10000, blank=True)

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.__unicode__()

    def get_absolute_url(self):
        return reverse('book_genre', args=[self.slug])

    def get_supgenre(self):
        supgenres = BookGenre.objects.filter(subgenres__id=self.id).all()  # .all()[0]
        if supgenres:
            return supgenres[0]
        else:
            return None

    def get_supgenres(self):
        supgenres = []
        genre = self.get_supgenre()
        if genre:
            supgenres.append(genre)
            supgenres = supgenres + genre.get_supgenres()

        import logging
        logging.debug("Supgenres: %s", supgenres)
        return supgenres

    def get_download_link(self):
        supgenres = self.get_supgenre()
        if supgenres:
            folders = supgenres.get_download_link()
        else:
            folders = path

        return folders + "/" + self.folder

    def preview(self):
        if self.image:
            return self.image.url()
        else:
            return ""

    class Meta:
        verbose_name = _('Book genre')
        verbose_name_plural = _('Book genres')
        ordering = ['title', ]


class ScienceBook(models.Model):
    authors = models.ManyToManyField(Person, verbose_name=_('Authors'), blank=True)
    genre = models.ManyToManyField('BookGenre', verbose_name=_('Genres'))
    title = models.CharField(_('Title'), max_length=255)
    slug = models.SlugField(_('Slug'), unique=True)
    folder = models.CharField(_('Folder'), max_length=255)
    image = models.ImageField(verbose_name=_('Image'), storage=image_fs, blank=True)
    description = models.TextField(_('Description'), max_length=10000, blank=True)

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.__unicode__()

    def get_absolute_url(self):
        return reverse('book', args=[self.slug])

    def get_authors_list(self):
        return ", ".join([str(a) for a in self.authors.all()])  # _set.all()

    def get_main_genre(self):
        if self.genre.all():
            return self.genre.all()[0]
        else:
            return None

    def get_download_link(self):
        folders = self.get_main_genre().get_download_link()  # "/".join([str(g.folder) for g in self.genre.all()])
        return folders + "/" + self.folder

    class Meta:
        verbose_name = _('Book')
        verbose_name_plural = _('Books')
        ordering = ['title', ]

src/book/views.py
from django.views.generic import ListView, DetailView
from book.models import BookGenre, ScienceBook
from django.shortcuts import redirect


class GenreListView(ListView):
    model = BookGenre


class WikiListView(ListView):
    model = BookGenre
    template_name = 'book/wiki_list.html'


class GenreView(DetailView):
    model = BookGenre


def random_book(request):
    book = ScienceBook.objects.order_by('?').first()
    return redirect(book.get_absolute_url())


class BookListView(ListView):
    model = ScienceBook


class BookView(DetailView):
    model = ScienceBook

templates/book/book_detail.html
{% extends 'book/bookgenre_detail.html' %}
{% load django_bootstrap_breadcrumbs %} 
{% load i18n %}

{% block title %} {{ book }} {% endblock %} 

{% block breadcrumbs %}
	{{ block.super }}
  {% for genre in book.get_main_genre.get_supgenres %}
    {% breadcrumb genre genre.get_absolute_url %}
  {% endfor %}
  {% breadcrumb book.get_main_genre book.get_main_genre.get_absolute_url %}
  {% breadcrumb book book.get_absolute_url %}
{% endblock %}

{% block pagehead %}
<div class="container">
  {% if book.authors.count %}
    <h2>{{ book.get_authors_list }}</h2>
  {% endif %}
  <h1>{{ book.title }}</h1>
  <ul class="edit-btns">
    <li><a href="{% url "admin:book_book_add" %}" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> {% trans "Add" %}</a></li>
    <li><a href="{% url "admin:book_book_change" book.id %}" class="btn btn-default"><span class="glyphicon glyphicon-pencil"></span> {% trans "Change" %}</a></li>
  </ul>
</div>
{% endblock %}

{% block content %}
<div class="col-md-12">
  <div class="col-md-6">
  {% if book.image %}
  <img src="{{ book.image.url }}" alt="{{ book.title }}" />
  {% endif %}
  <ul>
    <li><a href="{{ book.get_download_link }}">{% trans "Download" %}</a></li>
    <li><a href="//google.com/search?q={{ book.title }}">Google</a></li>
    <li><a href="//wikipedia.org/wiki/{{ book.title }}">Wikipedia</a></li>
    <li><a href="{% url "worlds_wiki" %}">Wiki</a></li>
  </ul>
  </div>

</div>
<div class="col-md-12">
{{ book.description | linebreaks }}
{{ world.get_wiki | safe }}
</div>
{% endblock %}

templates/book/book_list.html
{% extends 'base/list.html' %} 
{% load django_bootstrap_breadcrumbs %}
{% load i18n %}

{% block title %}{% trans "Books" %}{% endblock %} 

{% block breadcrumbs %}
	{{ block.super }}
	{% breadcrumb "Books" "books" %}
{% endblock %}

{% block pageheadtext %}{% trans "Books" %}{% endblock %}

{% block content %}
  <ul class="wall container">
    <li class="brick"><a href="{% url "admin:book_book_add" %}"><h1><span class="glyphicon glyphicon-plus"></span> {% trans "Add" %}</h1></a></li>
{% if object_list %}
    <li class="brick"><a href="{% url "random_book" %}"><h1>{% trans "Random" %}</h1></a></li>
	{% for book in object_list %}
    <li class="brick"><a href="{{ genre.get_absolute_url }}">
        <h5>{{ book.title }}</h5>
        {{ book.preview }}
    </a></li>
	{% endfor %}
{% endif %}
  </ul>
{% endblock %}

templates/book/bookgenre_detail.html
{% extends 'book/bookgenre_list.html' %}
{% load django_bootstrap_breadcrumbs %} 
{% load i18n %}

{% block title %} {{ bookgenre }} {% endblock %} 

{% block breadcrumbs %}
	{{ block.super }}
  {% for sup in bookgenre.bookgenre_set.all %}
  {% breadcrumb sup sup.get_absolute_url %}
  {% endfor %}
	{% breadcrumb bookgenre.title bookgenre.get_absolute_url %}
{% endblock %}

{% block prev %}<a{% if bookgenre.prev %} href="{{ bookgenre.prev.get_absolute_url }}"{% endif %} class="btn btn-default">{% if bookgenre.prev %}{{ bookgenre.prev.title }}{% endif %}</a>{% endblock %}
{% block next %}<a{% if bookgenre.next %} href="{{ bookgenre.next.get_absolute_url }}"{% endif %} class="btn btn-default">{% if bookgenre.next %}{{ bookgenre.next.title }}{% endif %}</a>{% endblock %}

{% block pagehead %}
<div class="container">
  <h1 class="col-md-10">
    {{ bookgenre.title }}
  </h1>
  <ul class="edit-btns">
    <li><a href="{% url "admin:book_bookgenre_add" %}" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> {% trans "Add" %}</a></li>
    <li><a href="{% url "admin:book_bookgenre_change" bookgenre.id %}" class="btn btn-default"><span class="glyphicon glyphicon-pencil"></span> {% trans "Change" %}</a></li>
  </ul>
</div>
{% endblock %}

{% block content %}
<div class="col-md-12">
  <div class="col-md-6">
  {% if bookgenre.image %}
  <img src="{{ bookgenre.image.url }}" alt="{{ bookgenre.title }}" />
  {% endif %}
  <ul>
    <li><a href="//google.com/search?q={{ bookgenre.title }}">Google</a></li>
    <li><a href="//wikipedia.org/wiki/{{ bookgenre.title }}">Wikipedia</a></li>
  </ul>
  </div>

  <div class="col-md-6">
  {% if bookgenre.subgenres.all %}
  <h5>{% trans "Subgenres" %}</h5>
  <ul>
    {% for sub in bookgenre.subgenres.all %}
      <li><a href="{{ sub.get_absolute_url }}">{{ sub }}</a></li>
    {% endfor %}
  </ul>
  {% endif %}
  </div>
</div>
<div class="col-md-12">
  <ul class="wall container">
    <li class="brick"><a href="{% url "admin:book_book_add" %}"><h1><span class="glyphicon glyphicon-plus"></span> {% trans "Add" %}</h1></a></li>
    <li class="brick"><a href="{% url "book_genre_wiki" bookgenre.slug %}"><h1>Wiki</h1></a></li>
    <li class="brick"><a href="{% url "book_genres_orphans" %}"><h1>{% trans "Orphans" %}</h1></a></li>
{% if bookgenre.book_set.all %}
    <li class="brick"><a href="{% url "random_book" bookgenre.slug %}"><h1>{% trans "Random" %}</h1></a></li>
	{% for book in bookgenre.book_set.all %}
    <li class="brick"><a href="{{ book.get_absolute_url }}">
        <h5>{{ book.title }}</h5>
        {{ book.preview }}
    </a></li>
	{% endfor %}
{% endif %}
  </ul>
{{ bookgenre.description | linebreaks }}
{{ world.get_wiki | safe }}
</div>
{% endblock %}

templates/book/bookgenre_list.html
{% extends 'base/list.html' %} 
{% load django_bootstrap_breadcrumbs %}
{% load i18n %}

{% block title %}{% trans "Genres" %}{% endblock %} 

{% block breadcrumbs %}
	{{ block.super }}
	{% breadcrumb "Genres" "book_genres" %}
{% endblock %}

{% block pageheadtext %}{% trans "Genres" %}{% endblock %}

{% block content %}
  <ul class="wall container">
    <li class="brick"><a href="{% url "admin:book_bookgenre_add" %}"><h1><span class="glyphicon glyphicon-plus"></span> {% trans "Add" %}</h1></a></li>
    <li class="brick"><a href="{% url "book_genres_wiki" %}"><h1>Wiki</h1></a></li>
    <li class="brick"><a href="{% url "book_genres_orphans" %}"><h1>{% trans "Orphans" %}</h1></a></li>
    <li class="brick"><a href="{% url "books" %}"><h1>{% trans "All" %}</h1></a></li>
{% if object_list %}
    <li class="brick"><a href="{% url "random_book" %}"><h1>{% trans "Random" %}</h1></a></li>
	{% for genre in object_list %}
    <li class="brick"><a href="{{ genre.get_absolute_url }}">
        <h5>{{ genre.title }}</h5>
        {{ genre.preview }}
    </a></li>
	{% endfor %}
{% endif %}
  </ul>
{% endblock %}

templates/book/wiki_list.html
{% load i18n %}
<pre>
!! {% trans "Genres" %}

{% for genre in object_list %}* [[Attach:{{ genre.get_attach_filename }} -> {{ genre.title }}]][[<<]]{{ genre.title }}
{% endfor %}
(:childlist:)
</pre>