src/blog/urls.py
# coding: utf-8
from django.conf.urls import url
from blog.views import NewsListView, NewsView


urlpatterns = [
    url(r'^$', NewsListView.as_view(), name='news'),
    url(r'^(?P<slug>[\w-]+)/$', NewsView.as_view(), name='news_article'),
]

src/newspaperizer/urls.py
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin

urlpatterns = i18n_patterns(
    # '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls')),
    url(r'^world/', include('world.urls')),
    url(r'^book/', include('book.urls')),
    url(r'^newspaper/', include('newspaper.urls')),
    url(r'^article/', include('article.urls')),
    url(r'^pdf/', include('pdf.urls')),
    url(r'^wiki/', include('wiki.urls')),
    url(r'', include('index.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/pdf/urls.py
#coding: utf-8
from django.conf.urls import url
from pdf.views import pdf_view


urlpatterns = [
    url(r'^(?P<np>[\w-]+)/(?P<year>\d+)/(?P<issue>\d+)/view.pdf$', pdf_view, name='pdf'),
]

src/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class News(models.Model):
    title = models.CharField(_('title'), max_length=255)
    slug = models.SlugField(_('slug'), unique=True)    
    date = models.DateField(_('date'))
    brief = models.TextField(_('brief'), max_length=512)
    description = models.TextField(_('description'), max_length=10000)

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.__unicode__()

    def get_absolute_url(self):
        return reverse('news_article', kwargs={"slug": self.slug, })

    class Meta:
        verbose_name = _('news')
        verbose_name_plural = _('news')
        ordering = ['date', ]

src/blog/views.py
from django.views.generic import ListView, DetailView
from blog.models import News


class NewsListView(ListView):
    model = News
    
    
class NewsView(DetailView):
    model = News

templates/blog/news_detail.html
{% extends 'blog/news_list.html' %}
{% load django_bootstrap_breadcrumbs %} 
{% load i18n %}

{% block title %} {{ news }} {% endblock %} 

{% block breadcrumbs %}
  {{ block.super }}
  {% breadcrumb news news.get_absolute_url %}
{% endblock %}

{% block pagehead %}
<div class="container">
  <h1>{{ news.title }}</h1>
  <ul class="edit-btns">
    <li><a href="{% url "admin:blog_news_add" %}" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> {% trans "Add" %}</a></li>
    <li><a href="{% url "admin:blog_news_change" news.id %}" class="btn btn-default"><span class="glyphicon glyphicon-pencil"></span> {% trans "Change" %}</a></li>
  </ul>
  <div>{{ news.date }}</div>
</div>
{% endblock %}

{% block content %}
<div class="col-md-12">
  <div>
  	{{ news.brief }}
  </div>
  <hr />
  <div>
	{{ news.description | linebreaks }}
  </div>
</div>
{% endblock %}

templates/blog/news_list.html
{% extends 'base/list.html' %} 
{% load django_bootstrap_breadcrumbs %}
{% load i18n %}

{% block title %}{% trans "News" %}{% endblock %} 

{% block breadcrumbs %}
	{{ block.super }}
	{% breadcrumb "News" "news" %}
{% endblock %}

{% block pageheadtext %}{% trans "News" %}{% endblock %}

{% block content %}
  <ul class="wall container">
    <li class="brick"><a href="{% url "admin:blog_news_add" %}"><h1><span class="glyphicon glyphicon-plus"></span> {% trans "Add" %}</h1></a></li>
{% if object_list %}
    <li class="brick"><a href="{% url "random_book" %}"><h1>{% trans "Random" %}</h1></a></li>
	{% for news in object_list %}
    <li class="brick"><a href="{{ news.get_absolute_url }}">
        <h4>{{ news.title }}</h4>
        <div>{{ news.date }}</div>
        {{ news.brief }}
    </a></li>
	{% endfor %}
{% endif %}
  </ul>
{% endblock %}