src/newspaper/urls.py
# coding: utf-8
from django.conf.urls import url
from newspaper.views import NewspaperListView, YearListView, IssueListView, ArticleListView, generate


urlpatterns = [
    url(r'^np/$', NewspaperListView.as_view(), name='newspapers'),
    url(r'^np/(?P<np>[\w-]+)/$', YearListView.as_view(), name='year'),
    url(r'^np/(?P<np>[\w-]+)/(?P<year>\d+)/$', IssueListView.as_view(), name='issues'),
    url(r'^generate/(?P<np>[\w-]+)/(?P<year>\d+)/(?P<issue>\d+)/$', generate, name='generate'),
    url(r'^np/(?P<np>[\w-]+)/(?P<year>\d+)/(?P<issue>\d+)/$', ArticleListView.as_view(), name='issue'),
]

src/newspaperizer/urls.py
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin

urlpatterns = i18n_patterns(
    # '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls')),
    url(r'^world/', include('world.urls')),
    url(r'^book/', include('book.urls')),
    url(r'^newspaper/', include('newspaper.urls')),
    url(r'^article/', include('article.urls')),
    url(r'^pdf/', include('pdf.urls')),
    url(r'^wiki/', include('wiki.urls')),
    url(r'', include('index.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/pdf/urls.py
#coding: utf-8
from django.conf.urls import url
from pdf.views import pdf_view


urlpatterns = [
    url(r'^(?P<np>[\w-]+)/(?P<year>\d+)/(?P<issue>\d+)/view.pdf$', pdf_view, name='pdf'),
]

src/newspaper/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _


class Newspaper(models.Model):
    title = models.CharField(_('title'), max_length=255)
    description = models.TextField(_('description'), max_length=10000, blank=True)
    slug = models.SlugField(_('slug'), unique=True)

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.__unicode__()

    def get_years(self):
        return self.issue_set.all()

    def url(self):
        return reverse('year', args=[self.slug])

    def prev(self):
        try:
            return Newspaper.objects.filter(id__lt=self.id).order_by('-id')[0]
        except (IndexError):
            return None

    def next(self):
        try:
            return Newspaper.objects.filter(id__gt=self.id).order_by('id')[0]
        except (IndexError):
            return None

    class Meta:
        verbose_name = _('newspaper')
        verbose_name_plural = _('newspapers')
        ordering = ['title', ]


class Year(models.Model):
    year = models.IntegerField(_('year'))

    def __unicode__(self):
        return self.year.__str__()

    def __str__(self):
        return self.__unicode__()

    def prev(self):
        try:
            return Year.objects.filter(year__lt=self.year).order_by('-year')[0]
        except (IndexError):
            return None

    def next(self):
        try:
            return Year.objects.filter(year__gt=self.year).order_by('year')[0]
        except (IndexError):
            return None

    class Meta:
        verbose_name = _('year')
        verbose_name_plural = _('years')
        ordering = ['year', ]


class Issue(models.Model):
    newspaper = models.ForeignKey('Newspaper', verbose_name=_('newspaper'), null=True)
    year = models.ForeignKey('Year', verbose_name=_('year'), null=True)
    date = models.DateField(_('date'))
    issue = models.IntegerField(_('issue'), default=0)
    description = models.CharField(_('description'), max_length=255, blank=True)

    def __unicode__(self):
        return "{} {}'{}".format(self.newspaper, self.issue, self.year)

    def __str__(self):
        return self.__unicode__()

    def url(self):
        return reverse('issue', args=[self.newspaper.slug, self.year, self.issue])

    def title_page(self):
        return self.article_set.get(page=1)

    class Meta:
        verbose_name = _('issue')
        verbose_name_plural = _('issues')
        ordering = ['newspaper', 'year', 'issue']

src/newspaper/views.py
from django.views.generic import ListView
from newspaper.models import Newspaper, Year, Issue
from article.models import Article
from template.models import ArticleTemplate
from django.shortcuts import redirect


def get_newspaper(slug):
    return Newspaper.objects.get(slug=slug)


def get_year(year):
    return Year.objects.get(year=year)


def get_issue(np, year, issue):
    return Issue.objects.get(newspaper=np, year=year, issue=issue)


def generate(request, **kwargs):
    newspaper_id = kwargs.get('np')
    year_id = kwargs.get('year')
    issue_id = kwargs.get('issue')
    np = get_newspaper(newspaper_id)
    year = get_year(year_id)
    issue = get_issue(np, year, issue_id)

    templates = ArticleTemplate.objects.filter(newspaper=np).all()
    print(kwargs)
    for template in templates:
        print()
        print(template)
        print(
            template.category,
            template.article_type,
            template.page,
        )
        print()
        page = Article(
            issue=issue,
            category=template.category,
            article_type=template.article_type,
            page=template.page,
        )
        print(page)
        print()
        print("Title: ", page.title)
        print("Category: ", page.category)
        print("Article Type: ", page.article_type)
        # page.linked,
        print(
            page.description,
        )
    return redirect(issue.url())


class NewspaperListView(ListView):
    model = Newspaper


class YearListView(ListView):
    model = Year

    def newspaper_id(self):
        return self.kwargs.get('np')

    def get_queryset(self):
        np = get_newspaper(self.newspaper_id())

        return self.model.objects.filter(issue__newspaper=np).distinct()

    def get_context_data(self, **kwargs):
        context = ListView.get_context_data(self, **kwargs)
        context.update({
            "np": get_newspaper(self.kwargs.get('np')),
        })
        return context


class IssueListView(ListView):
    model = Issue

    def newspaper_id(self):
        return self.kwargs.get('np')

    def year_id(self):
        return self.kwargs.get('year')

    def get_queryset(self):
        np = get_newspaper(self.newspaper_id())
        year = get_year(self.year_id())

        return self.model.objects.filter(newspaper=np, year=year).distinct()

    def get_context_data(self, **kwargs):
        np = get_newspaper(self.newspaper_id())
        year = get_year(self.year_id())

        context = ListView.get_context_data(self, **kwargs)
        context.update({
            "np": np,
            "year": year,
        })
        return context


class ArticleListView(ListView):
    model = Article

    def newspaper_id(self):
        return self.kwargs.get('np')

    def year_id(self):
        return self.kwargs.get('year')

    def issue_id(self):
        return self.kwargs.get('issue')

    def get_queryset(self):
        np = get_newspaper(self.newspaper_id())
        year = get_year(self.year_id())
        issue = get_issue(np, year, self.issue_id())

        return self.model.objects.filter(issue=issue).distinct()

    def get_context_data(self, **kwargs):
        np = get_newspaper(self.newspaper_id())
        year = get_year(self.year_id())
        issue = get_issue(np, year, self.issue_id())

        context = ListView.get_context_data(self, **kwargs)
        context.update({
            "np": np,
            "year": year,
            "issue": issue,
        })
        return context

    def dispatch(self, request, *args, **kwargs):
        np = get_newspaper(self.newspaper_id())
        year = get_year(self.year_id())
        issue = get_issue(np, year, self.issue_id())

        try:
            return redirect(issue.title_page().url())
        except Article.DoesNotExist:
            return super(ArticleListView, self).dispatch(request, *args, **kwargs)

templates/newspaper/issue_list.html
{% extends 'newspaper/year_list.html' %} 
{% load django_bootstrap_breadcrumbs %}
{% load i18n %}
{% block title %}{{ np.title }}'{{ year }} {% endblock %} 
{% block breadcrumbs %}
	{{ block.super }}
	{% breadcrumb year "issues" np.slug year %}
{% endblock %}
{% block pagehead %}
	<ul class="container">
		<li class="prev">{% block prev %}<a{% if year.prev %} href="{% url "issues" np.slug year.prev %}"{% endif %} class="btn btn-default">{% if year.prev %}{{ year.prev }}{% endif %}</a>{% endblock %}</li>
    <li class="next">{% block next %}<a{% if year.next %} href="{% url "issues" np.slug year.next %}"{% endif %} class="btn btn-default">{% if year.next %}{{ year.next }}{% endif %}</a>{% endblock %}</li>
	</ul>
	<div class="container">
		<h1 class="col-md-10">{% block pagetitle %}{{ np }}'{{ year }}{% endblock %}</h1>
		<div class="col-md-2">{% block pagesubtitle %}<div><a href="{%url "issues" np.slug year.year %}"><h4>{{ year }}</h4></a></div>{% endblock %}</div>
	</div>
{% endblock %}
{% block content %} 
	<div class="col-md-3">

		{% if object_list %}
		<ul>
			{% for issue in object_list %}
			<li><a href="{{ issue.url }}">{{ issue }}</a></li>
			{% endfor %}
		</ul>		
		{% else %}
    <div>{% trans "No newspapers" %}</div>
		{% endif %}
	</div>

	<div class="col-md-9">
		<div>
		   	{{ np.description }}
		</div>
	</div>
{% endblock %}

templates/newspaper/newspaper_list.html
{% extends 'base.html' %} 
{% load django_bootstrap_breadcrumbs %}
{% load i18n %}
{% block title %}{% trans "Newspapers" %}{% endblock %} 
{% block breadcrumbs %}
	{{ block.super }}
	{% breadcrumb "Newspapers" "newspapers" %}
{% endblock %}
{% block pagehead %}
<div class="container">
  <h1 class="col-md-10">{% trans "Newspapers" %}</h1>
</div>
{% endblock %}
{% block content %}
  <h2>{% trans "Newspapers" %}</h2>
{% if object_list %}
<ul>
	{% for newspaper in object_list %}
	<li><a href="{% url 'year' newspaper.slug %}">{{ newspaper.title }}</a></li>
	{% endfor %}
</ul>
{% else %}
  <div>{% trans "No newspapers" %}</div>
{% endif %}
{% endblock %}

templates/newspaper/year_list.html
{% extends 'newspaper/newspaper_list.html' %} 
{% load django_bootstrap_breadcrumbs %}
{% load i18n %}
{% block title %} {{ np }} {% endblock %} 
{% block breadcrumbs %}
	{{ block.super }}
	{% breadcrumb np.title "year" np.slug %}
{% endblock %}
{% block pagehead %}
	<ul class="container">
		<li class="prev">{% block prev %}<a{% if np.prev %} href="{{ np.prev.url }}"{% endif %} class="btn btn-default">{% if np.prev %}{{ np.prev }}{% endif %}</a>{% endblock %}</li>
    <li class="next">{% block next %}<a{% if np.next %} href="{{ np.next.url }}"{% endif %} class="btn btn-default">{% if np.next %}{{ np.next }}{% endif %}</a>{% endblock %}</li>
	</ul>
	<div class="container">
    <h1 class="col-md-10">{% block pagetitle %}{{ np.title }}{% endblock %}</h1>
	</div>
{% endblock %}
{% block content %} 
	<div class="col-md-3">

		{% if object_list %}
		<ul>
			{% for year in object_list %}
			<li><a href="{% url 'issues' np.slug year.year %}">{{ year }}</a></li>
			{% endfor %}
		</ul>		
		{% else %}
    <div>{% trans "No newspapers" %}</div>
		{% endif %}
	</div>

	<div class="col-md-9">
		<div>
		   	{{ np.description }}
		</div>
	</div>
{% endblock %}